### ISSUE TITLE
generated rst, missing single space between words

### ISSUE THREAD

**Issue by kbhawkey** [russell/fairy-slipper#11]
.. swagger:tag:: policies
   :synopsis: Policies

   Manages policies.

   You can encode policy rule sets into a blob to be consumed byremote
   services. To do so, set `type`to `application/json`and specify
   policy rules as JSON strings in a `blob`. For example:

**Comment by kbhawkey** [comment]
In the DocBook files, the para element may contain a newline character. The newline character appears
to be cleaned-up and no space inserted in the case where the text continues.  The errors show up in 
generated .json files, 'summary' tags, after docbkx_to_json processing. 

This may not be the only type of case, see ch_identity-v3-ext.xml, last para element has an embedded
link element with text.  The generated file, api-doc/identity-extensions/v3-tags.rst has the concatenated text as, `For more information, seeUse trusts`.  The actual link is missing.

**Comment by russell** [comment]
This can be a hard area to work in.  I think i must have recently introduced the bug by accident.  I did a bunch of work 26792a7d32ebb9a84cb921938d5a91b6dda85693 in that area.  I imagine that code is buggy and doesn't work when there is a newline.

Basically from what I remember, when we parse the WADL, we trim any whitespace and the we join the list of strings with a space. This must not be working in some cases.

We may have to consider writing a test to check that the WADL conversion is working in this case so that we don't break the parser in the future.

**Comment by russell** [comment]
OK, I have pushed a sample test for the wadl_to_swagger code.  It's pretty poor.  But It's enough to start basing other simple tests on.

**Comment by russell** [comment]
I have split the missing link content out into a separate issue, that way we a can at least have the illusion of progress!

**Comment by kbhawkey** [comment]
I looked into the missing single space in the para node.  In the case of text with inline markup, a space is added before and after the markup.  Good.  In the depart_para(), a join of the strings is made, though no space is placed between the elements in this list.  
I tested a join with a space and removed the additional spacing in the code literal and emphasis markup cases.  Looks fine.  Though, I see there are new lines sometimes included within the quoted markup.  Will look into a test for this case.
