### ISSUE TITLE
rst tables written out as plain text, not html tables, rest.py

### ISSUE THREAD

**Issue by kbhawkey** [russell/fairy-slipper#13]
I narrowed down a problem loading the page for a number of services that contain tables,
database v1, image v2, blockstorage v2, networking-extension v2, identity-extension v2.
Two problems:
1) There appears to be a problem with the method,
default_visit(self, node) in rest.py
This is called after the table is visited and the subsequent index is a string not an integer.
2) The tables in the various .rst files are correct, but the table nodes in rest.py are
written as text not html tables.  I added methods visit_table, depart_table verifying that the
node contains the table as html.

**Comment by russell** [comment]
They should be written has markdown style tables https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

@kbhawkey i apologize it's a bit crazy because we are writing a RST -> Markdown translator.  So you'll need to make it output a table in Markdown text format not HTML.

But, the good news is, that area actually has test!  there is a test_rest.py file, it has some simple conversion tests that you'll be able to extend.

**Comment by kbhawkey** [comment]
Tables are writing as Markdown.  Remaining work:
-Address table inline definintion lists, 
column spacing (use colwidth attribute on colspec node, tgroup node has col attribute), 
add new lines after table for spacing between body text.
-Rework handling of table paragraph and Text nodes (both contain the same text).  I would expect the processing of the inline markup to be simpler.  I have some ideas in this area and will continue to test this.

**Comment by kbhawkey** [comment]
I plan to close this issue.  The tables are writing markdown and basic testing is in place.
Further work needs to be done to style the tables and table elements.

**Comment by russell** [comment]
Great work!

I have added the markdown table rendering, I ended up hooking into the Marked renderer.  It was the method that would easily work in the end.
